const express = require('express')
const router = express.Router()
const passport = require('../middleware/passport')
const { login, register, verifyEmail, getProfile, checkAdmin } = require('../controllers/auth.controller')
const { checkRole } = require('../middleware/checkRole')
router.post('/register', register)
router.post('/login', passport.authenticate('local', { session: false }), login)
router.get('/verify-email/:token', verifyEmail)
router.get('/profile', passport.authenticate('bearer', { session: false }), getProfile)
router.get('/checkAdmin', checkRole(['admin']), checkAdmin)
module.exports = router