const express = require('express')
const router = express.Router()
const passport = require('../middleware/passport')
const { login, register, verifyEmail, forgotpassword, resetPasswordGet, resetPasswordPost, getProfile, verifyAdmin, verifyProjectManager, verifyUser } = require('../controllers/auth.controller')
const { checkRole } = require('../middleware/checkRole')
router.post('/auth/register', passport.authenticate('bearer', { session: false }), checkRole(['admin']), register)
router.post('/auth/login', passport.authenticate('local', { session: false }), login)
router.get('/auth/verify-email/:token', verifyEmail)
router.post('/auth/forgotpassword', forgotpassword)
router.get('/auth/reset/:token', resetPasswordGet)
router.post('/auth/reset/:token', resetPasswordPost)
router.get('/auth/profile', passport.authenticate('bearer', { session: false }), getProfile)
router.get('/auth/checkAdmin', passport.authenticate('bearer', { session: false }), checkRole(['admin']), verifyAdmin)
router.get('/auth/checkProjectManager', passport.authenticate('bearer', { session: false }), checkRole(['projectManager']), verifyProjectManager)
router.get('/auth/checkUser', passport.authenticate('bearer', { session: false }), checkRole(['user']), verifyUser)
module.exports = router