const express = require('express')
const router = express.Router()
const validator  = require('../validators/organization.validator')
const { getOrganizations, getOrganizationsById, createOrganization, updateOrganization, deleteOrganization } = require('../controllers/organization.controller')
router.get('/organization', getOrganizations)
router.get('/organization/:id', getOrganizationsById)
router.post('/organization', validator, createOrganization)
router.patch('/organization/:id', validator, updateOrganization)
router.delete('/organization/:id', deleteOrganization)
module.exports = router