const express = require('express')
const router = express.Router()
const validator = require('../validators/userMaster.validator')
const upload = require('../middleware/upload')
const { getUser, getUserByEmail, createUser, updateUser, deleteUser, getUserPopulate, createUserImage, deleteUserImage } = require('../controllers/userMaster.controller')
router.get('/user', getUser)
router.get('/user/:id', getUserByEmail)
router.post('/user', validator, createUser)
router.patch('/user/:id', validator, updateUser)
router.delete('/user/:id', deleteUser)
router.get('/user/:id/:fields', getUserPopulate)
router.post('/user/image/:id', upload.single('userImage'), createUserImage)
router.delete('/user/image/:id', deleteUserImage)
module.exports = router